import { Check, ChevronRight, Folder, Link as LinkIcon, Play, Pause, RotateCcw, Trophy, Trash2, Plus, ImagePlus } from 'lucide-react'
import type { DashboardBlock } from '../types'
import { useQuestboard } from '../store'
import { assetUrl, openExternal, pickFolder, pickImages } from '../platform'
export function BlockContent({block}:{block:DashboardBlock}){const s=useQuestboard();
 if(block.type==='quest')return <div className="quest-list">{s.quests.slice(0,6).map(q=><div key={q.id} className={`quest-row ${q.done?'done':''}`}><button className="quest-check" onClick={e=>{e.stopPropagation();s.toggleQuest(q.id)}}><span className="check-bubble">{q.done&&<Check size={13}/>}</span></button><span className="quest-title">{q.title}</span><b>+{q.xp}</b><button className="row-delete" onClick={()=>s.deleteQuest(q.id)}><Trash2 size={13}/></button></div>)}<button className="add-inline" onClick={()=>{const title=prompt('Quest title');if(!title)return;const raw=prompt('XP','80');s.addQuest(title,Math.max(10,Number(raw)||80))}}><Plus size={14}/> Add quest</button></div>
 if(block.type==='milestone'){const done=s.quests.filter(q=>q.done).length,total=Math.max(1,s.quests.length),pct=Math.round(done/total*100);return <div className="boss-card"><div className="boss-symbol"><Trophy size={22}/></div><div><span className="tiny-label">BOSS QUEST</span><h3>{s.activeProject} v1</h3></div><div className="boss-progress"><i style={{width:`${pct}%`}}/></div><div className="boss-foot"><span>{done} / {total} quests</span><strong>{pct}%</strong></div></div>}
 if(block.type==='stats'){const pct=Math.round(s.quests.filter(q=>q.done).length/Math.max(1,s.quests.length)*100);return <div className="stat-big"><strong>{pct}%</strong><span>project complete</span><div className="mini-ring">{s.level}</div></div>}
 if(block.type==='links')return <div className="link-stack">{s.links.slice(0,5).map(x=><div className="inline-item" key={x.id}><button onClick={()=>openExternal(x.url)}><LinkIcon size={15}/><span>{x.label}</span><ChevronRight size={14}/></button><button className="tiny-delete" onClick={()=>s.deleteLink(x.id)}><Trash2 size={12}/></button></div>)}<button className="add-inline" onClick={()=>{const label=prompt('Label');const url=label&&prompt('URL');if(label&&url)s.addLink(label,url)}}><Plus size={14}/> Add link</button></div>
 if(block.type==='folders')return <div className="folder-grid">{s.folders.slice(0,6).map(x=><div className="folder-item" key={x.id}><button onClick={()=>openExternal(x.path)}><Folder size={18}/><span>{x.label}</span></button><button className="tiny-delete" onClick={()=>s.deleteFolder(x.id)}><Trash2 size={11}/></button></div>)}<button className="folder-add" onClick={async()=>{const path=await pickFolder();if(path)s.addFolder(path.split(/[\\/]/).pop()||'Folder',path)}}><Plus size={18}/><span>Add folder</span></button></div>
 if(block.type==='note')return <textarea className="note-editor" value={s.note} onChange={e=>s.setNote(e.target.value)} onPointerDown={e=>e.stopPropagation()}/>
 if(block.type==='gallery')return <div className="gallery">{s.gallery.length?s.gallery.slice(0,8).map(x=><button className="shot image-shot" key={x.id} style={{backgroundImage:`url(${assetUrl(x.src)})`}} onDoubleClick={()=>s.deleteImage(x.id)}/>):<><div className="shot s1"/><div className="shot s2"/><div className="shot s3"/></>}<button className="gallery-add" onClick={async()=>s.addImages(await pickImages())}><ImagePlus size={18}/><span>Add</span></button></div>
 if(block.type==='focus'){const m=Math.floor(s.focusSeconds/60).toString().padStart(2,'0'),sec=(s.focusSeconds%60).toString().padStart(2,'0');return <div className="focus"><strong>{m}:{sec}</strong><span>Deep focus</span><div><button onClick={s.toggleFocus}>{s.focusRunning?<Pause size={15}/>:<Play size={15}/>} {s.focusRunning?'Pause':'Start'}</button><button onClick={s.resetFocus}><RotateCcw size={14}/></button></div></div>}
 if(block.type==='goal')return <div className="goal-card"><span>PRIMARY GOAL</span><strong>Ship {s.activeProject} v1</strong><p>Complete every boss dependency and reach a clean, usable release.</p></div>
 if(block.type==='activity')return <div className="activity-list">{s.activities.slice(0,7).map(a=><div key={a.id}><i/><span>{a.text}</span>{a.xp&&<b>+{a.xp}</b>}</div>)}</div>
 return null}
