import type { QuestboardState } from './types'
import { isTauri } from './platform'
const KEY='questboard-state-v1';let dbPromise:Promise<any>|null=null;let writeQueue:Promise<void>=Promise.resolve()
function normalize(raw:Partial<QuestboardState>|null):Partial<QuestboardState>|null{if(!raw||typeof raw!=='object')return null;const blocks=Array.isArray(raw.blocks)?raw.blocks.map(b=>({...b,detached:false})):undefined;return{...raw,blocks,version:1}}
async function db(){if(!isTauri())return null;if(!dbPromise)dbPromise=import('@tauri-apps/plugin-sql').then(async({default:Database})=>{const d=await Database.load('sqlite:questboard.db');await d.execute('PRAGMA journal_mode=WAL');await d.execute('PRAGMA synchronous=NORMAL');await d.execute('PRAGMA busy_timeout=3000');await d.execute(`CREATE TABLE IF NOT EXISTS app_state (id INTEGER PRIMARY KEY CHECK (id=1),payload TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`);return d});return dbPromise}
export async function loadState():Promise<Partial<QuestboardState>|null>{try{const d=await db();if(d){const rows=await d.select('SELECT payload FROM app_state WHERE id = 1') as {payload:string}[];if(rows[0]?.payload)return normalize(JSON.parse(rows[0].payload))}}catch(e){console.warn('SQLite load failed, falling back to localStorage',e)}try{const raw=localStorage.getItem(KEY);return normalize(raw?JSON.parse(raw):null)}catch{return null}}
export function saveState(state:QuestboardState):Promise<void>{const payload=JSON.stringify(state);try{localStorage.setItem(KEY,payload)}catch{};writeQueue=writeQueue.then(async()=>{try{const d=await db();if(d)await d.execute('INSERT INTO app_state(id,payload,updated_at) VALUES(1,$1,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET payload=$1, updated_at=CURRENT_TIMESTAMP',[payload])}catch(e){console.warn('SQLite save failed',e)}});return writeQueue}
export async function exportState(state:QuestboardState){const payload=JSON.stringify(state,null,2);if(!isTauri()){const blob=new Blob([payload],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='questboard-backup.json';a.click();URL.revokeObjectURL(a.href);return}const{save}=await import('@tauri-apps/plugin-dialog');const path=await save({defaultPath:'questboard-backup.json',filters:[{name:'Questboard backup',extensions:['json']}]});if(path){const{invoke}=await import('@tauri-apps/api/core');await invoke('write_backup',{path,payload})}}
export async function importState():Promise<Partial<QuestboardState>|null>{if(!isTauri())return null;const{open}=await import('@tauri-apps/plugin-dialog');const path=await open({multiple:false,filters:[{name:'Questboard backup',extensions:['json']}]});if(!path||Array.isArray(path))return null;const{invoke}=await import('@tauri-apps/api/core');const payload=await invoke<string>('read_backup',{path});const parsed=JSON.parse(payload);if(!parsed||typeof parsed!=='object'||!Array.isArray(parsed.blocks)||!Array.isArray(parsed.quests))throw new Error('This file is not a valid Questboard backup');return normalize(parsed)}
