import type { QuestboardState } from './types'
import { useQuestboard } from './store'
import { saveState } from './repository'
type Envelope={updatedAt:number;payload:QuestboardState}
const cleanUrl=(v:string)=>v.replace(/\/+$/,'')
function plainState(state:any):QuestboardState{const copy=JSON.parse(JSON.stringify(state));delete copy.hydrated;return copy as QuestboardState}
function safePayload(state:any):QuestboardState{const payload=plainState(state);payload.settings={...payload.settings,syncToken:'',lastSyncAt:0};return payload}
async function storeSyncTimestamp(ts:number){const current=useQuestboard.getState();const settings={...current.settings,lastSyncAt:ts};useQuestboard.setState({settings});await saveState(plainState(useQuestboard.getState()))}
export async function syncNow():Promise<'pulled'|'pushed'|'noop'>{const s=useQuestboard.getState(),cfg=s.settings;if(!cfg.syncEnabled||!cfg.syncUrl||!cfg.syncToken)return'noop';const base=`${cleanUrl(cfg.syncUrl)}/v1/state/${encodeURIComponent(cfg.syncWorkspace||'main')}`;const headers={Authorization:`Bearer ${cfg.syncToken}`};let remote:Envelope|null=null;const r=await fetch(base,{headers});if(r.ok)remote=await r.json();else if(r.status!==404)throw new Error(`Sync GET ${r.status}`);const localEdit=Number(localStorage.getItem('questboard-last-local-edit')||0);if(remote&&remote.updatedAt>cfg.lastSyncAt&&remote.updatedAt>localEdit){const localSettings=s.settings;const merged={...remote.payload,settings:{...remote.payload.settings,...localSettings,lastSyncAt:Date.now()}};useQuestboard.setState(merged as any);await saveState(plainState(useQuestboard.getState()));return'pulled'}if(localEdit>cfg.lastSyncAt||!remote){const res=await fetch(base,{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({payload:safePayload(s)})});if(!res.ok)throw new Error(`Sync PUT ${res.status}`);await storeSyncTimestamp(Date.now());return'pushed'}await storeSyncTimestamp(Date.now());return'noop'}
